### ISSUE TITLE
webpackConfig.htmlElements.headTags not working

### ISSUE THREAD

**Issue by codechavez** [fulls1z3/html-elements-webpack-plugin#2]
[x] bug report => check the README and search github for a similar issue or PR before submitting

index.html doesn't recognized the following code when added.  
 <% if (webpackConfig.htmlElements.headTags) { %>
        
        <%= webpackConfig.htmlElements.headTags %>
        <% } %>

It appears at the top of the page.

This is my head.config.js
module.exports = {
    link: [
      { rel: 'stylesheet', href: '/assets/bootstrap/dist/css/bootstrap.min.css' },
      { rel: 'stylesheet', href: '/assets/font-awesome/css/font-awesome.min.css' },
    ]
  };

This is my webpack.config.js
 new HtmlElementsWebpackPlugin ({
            headTags: require('./head-config')
        }),
Using VSCODE 
Angular 4.4.6

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =   6.11.5

**Comment by fulls1z3** [comment]
@codechavez you can refer to [ng-seed/universal](https://github.com/ng-seed/universal) for a working sample.
